### ISSUE TITLE
`weather.get_forecast` is being deprecated in favor of `weather.get_forecasts`

### ISSUE THREAD

**Issue by Qhilm** [FL550/dwd_weather#112]
## Version of home_assistant
2023.12.0

## Version of the custom_component
2.0.13

## Describe the bug
Error message in Home Assistant:

"Detected use of deprecated service `weather.get_forecast`"
"Use weather.get_forecasts instead which supports multiple entities."

**Comment by Qhilm** [comment]
ah, right. Ignore, I use this code in my configuration.yaml, I just need to figure out how to migrate it.

The error was very misleading, it really looks like it's a problem with the integration, it nowhere says "the yaml code must be updated"...

```yaml
template:
  - trigger:
    - platform: time
      at: "00:02:00"
    - platform: homeassistant
      event: start
    - platform: event
      event_type: event_template_reloaded
    action:
      - service: weather.get_forecast
        data:
          type: daily
        target:
          entity_id: weather.dwd_12345
        response_variable: weather_data
    sensor:
      - name: "Max temp today"
        unique_id: max_temp_today
        state: >-
          {{ weather_data.forecast[0].temperature }}
        unit_of_measurement: "°C"
      - name: "Min temp today"
        unique_id: min_temp_today
        state: >-
          {{ weather_data.forecast[0].templow }}
        unit_of_measurement: "°C"
```
