### ISSUE TITLE
Max Daily Temperature broken

### ISSUE THREAD

**Issue by Qhilm** [FL550/dwd_weather#127]
## Version of home_assistant

2024.5.3

## Version of the custom_component

2.1.2

## Describe the bug

The following code was working last year ([you suggested this](https://github.com/FL550/dwd_weather/issues/83#issuecomment-1749138379), many thanks again), it does not work anymore though:

```yaml
  - trigger:
    - platform: time
      at: "00:02:00"
    - platform: homeassistant
      event: start
    - platform: event
      event_type: event_template_reloaded
    action:
      - service: weather.get_forecasts
        data:
          type: daily
        target:
          entity_id: weather.dwd_station_redacted
        response_variable: weather_data
    sensor:
      - name: "Max temp today"
        unique_id: max_temp_today
        state: >-
          {{ weather_data['weather.dwd_station_redacted'].forecast[0].temperature }}
        unit_of_measurement: "°C"
      - name: "Min temp today"
        unique_id: min_temp_today
        state: >-
          {{ weather_data['weather.dwd_station_redacted'].forecast[0].templow }}
        unit_of_measurement: "°C"
```

The entity `sensor.max_temp_today` seems to show the minimum daily temperature now, instead of the maximum. It feels like the data structure has changed. If there is a place where I can look this up, please point me in the right direction. I went to the [DWD OpenData page](https://www.dwd.de/DE/leistungen/opendata/opendata.html) but it does not seem there is a description of the data format.

"Force hourly data update" is enabled for me, but I notice that data type is set to "daily" in this yaml, I wonder if there is a conflict.

## Debug log

There are no errors in the logs, as far as I can tell.
