### ISSUE TITLE
`sensor.sun_irradiance_<location>` is broken

### ISSUE THREAD

**Issue by nikipore** [FL550/dwd_weather#23]
## Version of home_assistant
core-2021.3.4

## Version of the custom_component
v1.2.8

## Describe the bug
`sensor.sun_irradiance_<location>` doesn't contain any data:

```
data: 
- datetime: '2021-03-31T16:00:00.000Z'
  value: null
- datetime: '2021-03-31T17:00:00.000Z'
  value: null
...
```
