### ISSUE TITLE
Use max temperature today in automation

### ISSUE THREAD

**Issue by hobbes444** [FL550/dwd_weather#50]
**Describe the solution you'd like**

I an trying to create an automation based on the daily max temperature. Say for example, if temperature will rise above 28°C, close blinds. (it's more complex than this, I am only closing if the sun is hitting the particular window, but the daily max temperature should be a condition for the automation to run, hence I think I need it to be a sensor).

**Describe alternatives you've considered**

I have enabled ```sensor.temperature_<entity_name>```, but that only gives the current temperature.

**Comment by hobbes444** [comment]
Thanks a lot, the windows are facing east (ish), so this is good enough for me.

The frustrating thing is, the daily max _is_ visible in the "weather forecast" card in HA, so I thought this could be pulled into a sensor.

**Comment by nikipore** [comment]
This is what I did for the very same purpose, but I found that what one actually needs for climate control isn't „today“ in terms of midnight or next 24 hours but in terms of day and night:
```yaml
template:
  - sensor:
      - name: weather_hourly_forecast_index_next_rising
        state: >
          {{ max(0, (as_timestamp(state_attr('sun.sun', 'next_rising')) - as_timestamp(state_attr('weather.dwd_weather_1h', 'forecast')[0]['datetime'])) // 3600) }}
      - name: weather_hourly_forecast_index_next_setting
        state: >
          {{ max(0, (as_timestamp(state_attr('sun.sun', 'next_setting')) - as_timestamp(state_attr('weather.dwd_weather_1h', 'forecast')[0]['datetime'])) // 3600) }}
      - name: weather_forecast_temperature_high
        state_class: measurement
        unit_of_measurement: "°C"
        state: >
          {{ state_attr('sensor.temperature_1h', 'data')[:(states('sensor.weather_hourly_forecast_index_next_setting') | int(0)) + 1] | map(attribute='value') | max | float(0) }}
        device_class: temperature
      - name: weather_forecast_temperature_low
        state_class: measurement
        unit_of_measurement: "°C"
        state: >
          {{ state_attr('sensor.temperature_1h', 'data')[:(states('sensor.weather_hourly_forecast_index_next_rising') | int(0)) + 1] | map(attribute='value') | min | float(0) }}
        device_class: temperature
```

Since I am on vacation I am posting this on my smartphone, so no guarantee for correct syntax/indentation, but the idea should be clear.

I decide when to open/close window and roof covers with a combination of actual (inside/outside) and high/low forecast temperatures, window position w.r.t. sun (Node-RED library [sun-position](https://github.com/rdmtc/node-red-contrib-sun-position)) plus forecast of sun intensity ([forecast.solar](https://www.home-assistant.io/integrations/forecast_solar/) integration).

**Comment by FL550** [comment]
Hi, you could also use the max and min values for the configured time interval from the weather entity directly like this:

```
template:
  - sensor:
      - name: Höchsttemperatur
        unit_of_measurement: °C
        state: >-     {{ state_attr("weather.dwd_weather_bad_homburg", "forecast")[0]["temperature"] }}
      - name: Tiefsttemperatur
        unit_of_measurement: °C
        state: >-           {{ state_attr("weather.dwd_weather_bad_homburg", "forecast")[0]["templow"] }}

```
If you want the next day, replace the 0 with a 1 and so on.
