### ISSUE TITLE
Where do I find the forecasts after update to the current version?

### ISSUE THREAD

**Issue by slecram** [FL550/dwd_weather#77]
## Version of home_assistant
2023.9.2

Where do I find the forecasts after update to the current version?

![image](https://github.com/FL550/dwd_weather/assets/62532513/91914e2e-1e2b-455a-8a8a-72a5e523eb7c)

**Comment by arboeh** [comment]
I have the same problem with Home Assistants 'Custom Weather Card'. It doesn't work any more, because the forecast attribute is missing.

**Comment by FL550** [comment]
Unfortunately it had to be removed due to changes in HA: [Forecast Attribute](https://www.home-assistant.io/blog/2023/09/06/release-20239/#weather-forecast-service)

I primarily suggest, that you inform the developer of your custom card to adapt as well. However I could provide the forecast as a separate sensor if requested.

**Comment by heikone** [comment]
The forecast attribute was a very useful feature for me.
I've used this by the following code:

```
template:
  - sensor:
      - name: "Temperatur DWD Waltrop Heute Min"
        unique_id: temperatur_dwd_waltrop_forecast_0_temp_min
        state: "{{state_attr('weather.waltrop_abdinghof','forecast')[0]['templow'] | float(0) }}"
        unit_of_measurement: "°C"
        device_class: temperature
```

Could anybody supply a code example, how to get current day's min and max expected temperature from DWD prediction?

Greetings
Heiko

**Comment by slecram** [comment]
`template:
  - trigger:
      - platform: time_pattern
        hours: "/1"
      - platform: homeassistant
        event: start
      - platform: event
        event_type: event_template_reloaded
    action:
      - service: weather.get_forecast
        data:
          type: daily
        target:
          entity_id: weather.salzuflen_bad_salzuflen_bad
        response_variable: forecast
    sensor:
      - name: wetter_temp_vorhersage_heute_max
        unique_id: wetter_temp_vorhersage_heute_max
        state: "{{ forecast.forecast[0].temperature}}"
        unit_of_measurement: "°C"
      - name: wetter_temp_vorhersage_heute_min
        unique_id: wetter_temp_vorhersage_heute_min
        state: "{{ forecast.forecast[0].templow}}"
        unit_of_measurement: "°C"`

**Comment by heikone** [comment]
Thanks a lot. That works!

Here, you can find the code:
```
template:
    - trigger:
          - platform: time_pattern
            hours: "/1"
          - platform: homeassistant
            event: start
          - platform: event
            event_type: event_template_reloaded
        action:
          - service: weather.get_forecast
            data:
              type: daily
            target:
              entity_id: weather.dwd_waltrop_abdinghof
            response_variable: forecast
        sensor:
          - name: "DWD Waltrop-Abdinghof Vorhersage Heute Max"
            unique_id: dwd_waltrop_abdinghof_forecast_today_max
            state: "{{ forecast.forecast[0].temperature}}"
            unit_of_measurement: "°C"
          - name: "DWD Waltrop-Abdinghof Vorhersage Heute Min"
            unique_id: dwd_waltrop_abdinghof_forecast_today_min
            state: "{{ forecast.forecast[0].templow}}"
            unit_of_measurement: "°C"
```

Greetings,
Heiko
