### ISSUE TITLE
Maximum temperatur of current day?

### ISSUE THREAD

**Issue by jmerifjKriwe** [FL550/dwd_weather#80]
How can I get the maximum forecast temperatur for the current day?
Before the update I used

`{{ state_attr('weather.myforecast', 'forecast')[0].temperature }}`

But how can I get this after the update?

**Comment by jmerifjKriwe** [comment]
Ok, found myself. 
I don't think it's easier now, but that's not an issue of dwd_weather.

Have a look in this thread for ideas: https://community.home-assistant.io/t/petition-dont-delete-the-forecast-attribute/609298

**Comment by heikone** [comment]
The forecast attribute was a very useful feature for me.
I've used this by the following code:

```
template:
  - sensor:
      - name: "Temperatur DWD Waltrop Heute Min"
        unique_id: temperatur_dwd_waltrop_forecast_0_temp_min
        state: "{{state_attr('weather.waltrop_abdinghof','forecast')[0]['templow'] | float(0) }}"
        unit_of_measurement: "°C"
        device_class: temperature
```

Could anybody supply a code example, how to get current day's min and max expected temperature from DWD prediction?

Greetings
Heiko
