### ISSUE TITLE
Maximum forecasted temperature for today in v2 version?

### ISSUE THREAD

**Issue by Qhilm** [FL550/dwd_weather#83]
## Version of home_assistant
2023.09.2

## Version of the custom_component
2.0.1

## Describe the bug
In previous version I used the code documented in closed issue #80 

```yaml
template:
  - sensor:
      - name: "Temperatur DWD Waltrop Heute Min"
        unique_id: temperatur_dwd_waltrop_forecast_0_temp_min
        state: "{{state_attr('weather.waltrop_abdinghof','forecast')[0]['templow'] | float(0) }}"
        unit_of_measurement: "°C"
        device_class: temperature
```

Question: how to rewrite this code for v2 of the integration? I'm struggling a bit.

**Comment by FL550** [comment]
I will integrate this for you in the next few days as a new sensor 😉

**Comment by Qhilm** [comment]
Just to be specific, I use both max and min forecasted temperatures for today, not just minimum as depicted in the sample code. Probably obvious, but just in case.

**Comment by FL550** [comment]
Ok, I have spent another thought about this and i think it is no good idea to implement this as a sensor in the integration. This will more or less counteract the newly introduced change in v2.

However, you can achive your request with this:

```
template:
- trigger:
    - platform: time
      at: "00:00:01"
    - platform: homeassistant
      event: start
    - platform: event
      event_type: event_template_reloaded
  action:
    - service: weather.get_forecast
      data:
        type: daily
      target:
        entity_id: {INSERT WEATHER ENTITY HERE}
      response_variable: weather_data
  sensor:
    - name: "Max temp"
      unique_id: max_daily_temp
      state: >-
        {{ weather_data.forecast[0].temperature }}
      unit_of_measurement: "°C"
    - name: "Min temp"
      unique_id: min_daily_temp
      state: >-
        {{ weather_data.forecast[0].templow }}
      unit_of_measurement: "°C"
```
