### ISSUE TITLE
How to use Template Weather Provider with new version ?

### ISSUE THREAD

**Issue by rolandsteinmeyer** [FL550/dwd_weather#90]
## Version of home_assistant
Home Assistant 2023.10.1

## Version of the custom_component
V2.0.4
## Describe the bug
I use a Template Weather Provider to add local messurements of my own weather station (temp, humidity, wind etc) to the data provided from dwd_weather for my location. This has stopped working. 
The online documentation [https://www.home-assistant.io/integrations/weather.template/](url) has the following example, which is what I have been using so far:

```

# Example configuration.yaml entry
weather:
  - platform: template
    name: "My Weather Station"
    condition_template: "{{ states('weather.my_region') }}"
    temperature_template: "{{ states('sensor.temperature') | float }}"
    temperature_unit: "°C"
    humidity_template: "{{ states('sensor.humidity') | float }}"
    forecast_daily_template: "{{ state_attr('weather.my_region', 'forecast') }}"
```

but this seems to work no longer, because the forecast attribute is missing. The documentation may not be up to date. 
(I have adjusted to  the new name for the weather station after the update in dwd_weather)

[Release notes for HA 2023.9 ](https://www.home-assistant.io/blog/2023/09/06/release-20239/#weather-forecast-service)advise to use the "newly added action part of a template entity", but I am clueless how to to this.

## Debug log

```text

Add your logs here.

```

**Comment by FL550** [comment]
Hi, the template sensors should have the option to declare actions and triggers. I have however no experience with the weather template integration. Nevertheless here is an example for a normal template sensor, which might be helpful for your tinkering:
```
template:
- trigger:
    - platform: time
      at: "00:00:01"
    - platform: homeassistant
      event: start
    - platform: event
      event_type: event_template_reloaded
  action:
    - service: weather.get_forecast
      data:
        type: daily
      target:
        entity_id: {INSERT WEATHER ENTITY HERE}
      response_variable: weather_data
  sensor:
    - name: "Max temp"
      unique_id: max_daily_temp
      state: >-
        {{ weather_data.forecast[0].temperature }}
      unit_of_measurement: "°C"
    - name: "Min temp"
      unique_id: min_daily_temp
      state: >-
        {{ weather_data.forecast[0].templow }}
      unit_of_measurement: "°C"
```

**Comment by rolandsteinmeyer** [comment]
Thanks for the update. If I use a trigger based template this way I now can get a **sensor** entity with attribute forecast which contains the forecast. But I think I need this in a **weather** entity to use it for the Template Weather Provider, because it seems to expect this in _forecast_daily_template_

**Comment by rolandsteinmeyer** [comment]
Some further Info: I was able to create a trigger based sensor that gives me the weather forcast as a sensor like this:
(weather.berlin is a dwd weather entity)

```
template:
  - trigger:
    - platform: time_pattern
      hours: /1
    - platform: homeassistant
      event: start
    - platform: event
      event_type: event_template_reloaded
    action:
      - service: weather.get_forecast
        data:
          type: daily
        target: 
          entity_id: weather.berlin
        response_variable: daily
    sensor:
      - name: "DWD myplace daily"
        unique_id: weather_forecast_myplace_daily
        state: "{{ now().isoformat() }}"
        attributes:
            forecast: "{{ daily.forecast }}"


```

This should make it possible to construct a new weather entity with a weather template sensor that combines forcast and condition from the dwd integration with messurements from my own weather station (sensor.elv_weather_station_...)  like this:


```


## weather template
weather:
  - platform: template
    name: "Wetterstation myplace"
    condition_template: "{{ states('weather.berlin') }}"    
    temperature_template: "{{ states('sensor.elv_weather_station_out_temp')  }}"
    temperature_unit:  '°C'
    humidity_template: "{{ states('sensor.elv_weather_station_out_humidity')  }}"
    forecast_daily_template: "{{ state_attr('sensor.dwd_myplace_daily', 'forecast') }}"
    pressure_template: "{{ states('sensor.elv_weather_station_abs_baro') }}"
    pressure_unit: "mbar"
    wind_speed_template:  "{{ states('sensor.elv_weather_station_wind_speed') }}"
    wind_speed_unit: "km/h"
    wind_bearing_template: "{{ states('sensor.elv_weather_station_wind_dir') }}"

```

But no luck so far - I get errors like this in HA log:


```
Logger: homeassistant.components.template.template_entity
Source: components/template/template_entity.py:220
Integration: Template (documentation, issues)


Error validating template result '[{'datetime': '2023-11-04T00:00:00Z', 'condition': 'rainy', 'wind_bearing': 148.93, 'wind_gusts': 9.26, 'precipitation_probability': 76, 'temperature': 10.0, 'templow': 7.0, 'wind_speed': 5.66, 'precipitation': 2.7}, {'datetime': '2023-11-05T00:00:00Z', 'condition': 'rainy', 'wind_bearing': 197.29, 'wind_gusts': 12.86, 'precipitation_probability': 74, 'temperature': 11.0, 'templow': 8.0, 'wind_speed': 6.69, 'precipitation': 10.6}, {'datetime': '2023-11-06T00:00:00Z', 'condition': 'rainy', 'wind_bearing': 216.71, 'wind_gusts': 9.77, 'precipitation_probability': 61, 'temperature': 12.0, 'templow': 6.0, 'wind_speed': 5.66, 'precipitation': 2.4}, 

(...)
 renders=4>' for attribute '_forecast_daily' in entity weather.wetterstation_myplace validation message 'Only valid keys in Forecast are allowed, unallowed keys: ({'wind_gusts'}), see Weather documentation https://www.home-assistant.io/integrations/weather/'

```
if I look up the [documentation page](https://www.home-assistant.io/integrations/weather/) that is mentioned in the error above there is a state attribute "wind_gust_speed" but no attribute "wind_gusts". Maybe this can be corrected in the forecast output of the dwd integration ?
